<a href="https://colab.research.google.com/github/ananyamohapatra20/Machine_Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy-Numerical Python
<br>
Advantages of Numpy:<br>
Allows several Mathematical Operations<br>
Faster Opertaions

In [74]:
import numpy as np

Numpy Vs List

In [75]:
from time import process_time

Time Taken By a List

In [76]:
python_list=[i for i in range(10000)]

start_time= process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()
print(end_time - start_time)

0.0012969279999985872


Time taken by Numpy Array

In [77]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array+=5

end_time = process_time()

print(end_time - start_time)

0.0002346100000032436


Numpy Array

In [78]:
np_array=np.array([1,2,3,4])
np_array


array([1, 2, 3, 4])

In [79]:
type(np_array)

numpy.ndarray

In [80]:
np_array.shape

(4,)

2D ARRAY

In [81]:
a=np.array([(1,2,3,4),(5,6,7,8)])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [82]:
a.shape

(2, 4)

In [83]:
b=np.array([(1,2,3,4,5),(92,35,8,9,3)],dtype=float)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [92., 35.,  8.,  9.,  3.]])

Initial Placeholders in Numpy array

In [84]:
#Create a numpy array of zeros
x=np.zeros((2,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
#Create a numpy array of ones
y=np.ones((2,4))
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [86]:
#array of particular value
z=np.full((3,4),9)
z

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [87]:
#Create an identity matrix
i=np.eye(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
# Create a numpy array with random values
r=np.random.random((3,3))
r

array([[0.68830369, 0.95447495, 0.03378051],
       [0.74028224, 0.23904267, 0.56302376],
       [0.80640394, 0.78355892, 0.62797858]])

In [89]:
#Create a numpy array with random integer value
v=np.random.randint(10,30,(3,4))
v

array([[13, 12, 22, 27],
       [16, 19, 11, 23],
       [23, 21, 14, 28]])

In [90]:
#Array of evenly spaced values (specifying the number of value required)
n=np.linspace(10,30,5)
n

array([10., 15., 20., 25., 30.])

In [91]:
#Array of evenly spaced values (specifying the step)
e = np.arange(10,30,3)
e

array([10, 13, 16, 19, 22, 25, 28])

In [92]:
#Convert list to array
list1=[1,2,3,5,6]
arr=np.asarray(list1)
print(arr)
type(arr)

[1 2 3 5 6]


numpy.ndarray

Analysing a numpy array

In [93]:
d=np.random.randint(30,80,(3,3))
d

array([[54, 41, 34],
       [44, 63, 43],
       [62, 77, 42]])

In [94]:
#Array Dimentions
print(d.shape)

(3, 3)


In [95]:
# number of dimensions #1D #2D
print(d.ndim)

2


In [96]:
#number of elements in an array
print(d.size)

9


In [97]:
#checking the datatype of values in the array
print(d.dtype)

int64


Mathematical opertaions on a Numpy array

In [98]:
list2 = [1,2,3,4,5,6]
list3 = [9,8,10,11,12]
print(list2 + list3) #concatenate or join two list

[1, 2, 3, 4, 5, 6, 9, 8, 10, 11, 12]


In [99]:
p=np.random.randint(10,20,(3,4))
q=p=np.random.randint(30,60,(3,4))
print(p)
print(q)


[[54 56 41 49]
 [34 34 56 41]
 [49 30 32 56]]
[[54 56 41 49]
 [34 34 56 41]
 [49 30 32 56]]


In [100]:
print(p + q)
print(p - q)
print(p * q)
print(p / q)

[[108 112  82  98]
 [ 68  68 112  82]
 [ 98  60  64 112]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2916 3136 1681 2401]
 [1156 1156 3136 1681]
 [2401  900 1024 3136]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [101]:
print(np.add(p,q))
print(np.subtract(p,q))
print(np.multiply(p,q))
print(np.divide(p,q))

[[108 112  82  98]
 [ 68  68 112  82]
 [ 98  60  64 112]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[2916 3136 1681 2401]
 [1156 1156 3136 1681]
 [2401  900 1024 3136]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Array manipulation


In [102]:
array=np.random.randint(2,40,(4,3))
array

array([[27,  7,  3],
       [14, 18, 26],
       [ 5, 30, 30],
       [21, 14, 22]])

In [103]:
#Transpose
trans=np.transpose(array)
print(trans)

[[27 14  5 21]
 [ 7 18 30 14]
 [ 3 26 30 22]]


In [104]:
array=np.random.randint(2,40,(4,3))
print(array)
print(array.shape)


[[24 20 10]
 [36 38  6]
 [18  3 14]
 [39 33 11]]
(4, 3)


In [105]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[24 36 18 39]
 [20 38  3 33]
 [10  6 14 11]]
(3, 4)


In [106]:
#Reshaping a array
array1=np.random.randint(2,30,(3,2))
array1


array([[23, 16],
       [23, 18],
       [14,  8]])

In [107]:
b=array1.reshape(2,3)
print(b)
print(b.shape)

[[23 16 23]
 [18 14  8]]
(2, 3)
